version: '3.7'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD : postgres 
      POSTGRES_USER: postgres
      POSTGRES_DB:  
    volumes: 
      - ./pgdata:/var/lib/postgresql/data 
    ports: 
    - 5432:5432

  web:
    build: 
      context: . 
    depends_on: 
      - db
    ports:
      - "3000:3000"
  